project:
  type: website
  output-dir: docs

website:
  title: "Bret Bosma Research"
  site-url: https://bretbosma.github.io/bosmab/
  search: false
  favicon: favicon.ico
  navbar:
    id: top-nav
    pinned: true
    toggle-position: right
    right:
      - href: index.qmd
        text: Home
      - href: bretbosma2026cv.pdf
        text: cv
        target: _blank
      - href: pubs.qmd
        text: pubs
      - href: blog.qmd
        text: Blog

brand:
  light: _brand-light.yml
  dark: _brand.yml


format:
  html:
    theme: styles.scss
    respect-user-color-scheme: true


execute:
  freeze: auto