project:
  type: website
  output-dir: docs

website:
  title: "Bret Bosma Research"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: bretbosma2026cv.pdf
        text: cv
        target: _blank
      - href: blog.qmd
        text: Blog

brand:
  light: _brand-light.yml
  dark: _brand.yml


format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "figtree"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto